package reverse_eng.com.model;
// Generated Jan 4, 2018 1:20:52 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserEmail generated by hbm2java
 */
@Entity
@Table(name = "user_email", catalog = "reverse_eng")
public class UserEmail implements java.io.Serializable {

	private int id;
	private User user;
	private String email;

	public UserEmail() {
	}

	public UserEmail(int id) {
		this.id = id;
	}

	public UserEmail(int id, User user, String email) {
		this.id = id;
		this.user = user;
		this.email = email;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "email", length = 211)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
